spring:
  datasource:
    url: jdbc:mysql://localhost:3306/second_hand_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 196888mfk
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    lazy-initialization: true

mybatis-plus:
  mapper-locations: classpath*:com/qcq/second_hand/mapper/xml/*.xml
  type-aliases-package: com.qcq.second_hand.entity
  configuration:
    mapUnderscoreToCamelCase: true
    default-fetch-size: 100
    default-statement-timeout: 30
    call-setters-on-nulls: true

  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      schema-run: false

server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

logging:
  level:
    root: DEBUG
    com.qcq.second_hand: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
wechat:
  appid: wx454f609b500bd5be
  secret: c7441762dc359dbec5ea3dc17cdcfc7a