spring:
  datasource:
    url: jdbc:mysql://localhost:3306/second_hand_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 196888mfk
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

mybatis-plus:
  mapper-locations: classpath*:com/qcq/second_hand/mapper/xml/*.xml
  type-aliases-package: com.qcq.second_hand.entity
  configuration:
    mapUnderscoreToCamelCase: true
    default-fetch-size: 100
    default-statement-timeout: 30
    call-setters-on-nulls: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8090
  servlet:
    context-path: /
  tomcat:
    max-connections: 8192
    accept-count: 100
    max-threads: 200
    min-spare-threads: 10

logging:
  level:
    root: INFO
    com.qcq.second_hand: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.apache.ibatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
